### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Thexiyang** [gatech-genemark/Mgcod#1]
Thanks for this great tool! Is it possible to install the software with one single command `conda install Mgcod`?

**Comment by arpfennig** [comment]
Hi,

Thanks for your interest in Mgcod. We don't have a conda package because of the dependency on MetaGeneMark, distributed under a separate license. I recommend creating a conda env using the provided `environment.yml` and running Mgcod from within there. 

Best,
Aaron

**Comment by Thexiyang** [comment]
Thanks. Could you please provide more guide on how to set MetaGeneMark? There is no v2 for this software in the http://exon.gatech.edu/GeneMark/license_download.cgi

**Comment by arpfennig** [comment]
Hi,

Bioconda was friendly enough to add the package. So now it can be installed using `conda install -c bioconda mgcod`. 

The MetaGeneMark binary is included in the distributions, but it will try to locate a GeneMark license key file. Therefore, you will still need to agree to the license for MetaGeneMark and download a license key file. The GeneMark key should be located in `$HOME/.gm_key`. 

Best,
Aaron
